### ISSUE TITLE
Diseñar el importador en varios pasos

### ISSUE THREAD

**Issue by IgnacioMaestro** [IgnacioMaestro/ampa-manager#235]

**Comment by klautern** [comment]
Ideas:

**PASO 1: Carga del excel**
**PASO 2: Acciones que se llevarán a cabo con posibilidad de modicarlas** 
- por cada fila del excel
  - por cada modelo
    - celdas del excel
    - [accion que se llevara a cabo (crear, modificar, nada, ...)](https://github.com/IgnacioMaestro/ampa-manager/blob/main/software_components/app_server/ampa_members_manager_project/ampa_manager/utils/processing_state.py)
    - campos modificados (si se modifica alguno)
    - instancia del modelo seleccionada (si se ha seleccionado alguna)
    - otras instancias del modelo (para que el usuario pueda cambiarlo manualmente)
    - errores
    - avisos

**PASO 3: Acciones llevadas a cabo**
- por cada fila del excel
- guardar listado de acciones en una tabla de importaciones para posibles consultas posteriores

**Comment by IgnacioMaestro** [comment]
Hacer un modelo del dominio de la importación

**Comment by klautern** [comment]
IMPORTACION
- Tipo: custodia, extraescolares, socios, campamentos
- Fecha importacion
- Edicion de custodia
- Edicion de estraescolares
- Edicion de campamentos
- Curso academico

FILAS (CHILD+apellidos familia+asistencia, PARENT+iban)
- Importacion (FK)
- nº fila (int)
- datos excel (JSON)
- procesado (bool)

MODELOS
- modelo (NO EDITABLE)
- instancia 
- accion propuesta: CREAR, MODIFICAR, 
- correcciones sobre los campos del excel del modelo (JSON)

	COMUNES: FAMILY, HOLDER, BANK ACCOUNT, CHILD, PARENT
	CUSTODIA: CUSTODY REGISTRATION
	EXTRAESCOLARES: AFTER-SCOOL REGISTRATION
	CAMPAMENTOS: CAMPS REGISTRATION
	SOCIOS: CHILD 2, CHILD 3, PARENT 2

**Comment by IgnacioMaestro** [comment]
En el administrador de Django, puedes mostrar varios modelos en una sola tabla utilizando la opción de herencia de modelos. La herencia de modelos te permite crear un modelo base y luego derivar otros modelos de él. Luego, puedes usar estos modelos derivados en el administrador de Django y mostrarlos en una sola tabla.

A continuación, te proporciono un ejemplo básico de cómo hacer esto:

Supongamos que tienes dos modelos similares llamados `ModeloA` y `ModeloB`. Puedes crear un modelo base llamado `ModeloBase` y luego derivar `ModeloA` y `ModeloB` de él. Luego, puedes registrar `ModeloA` y `ModeloB` en el administrador de Django.

```python
# models.py
from django.db import models

class ModeloBase(models.Model):
    campo_comun = models.CharField(max_length=255)

    class Meta:
        abstract = True  # Hace que este modelo sea abstracto y no se cree en la base de datos

class ModeloA(ModeloBase):
    campo_adicional_a = models.CharField(max_length=255)

class ModeloB(ModeloBase):
    campo_adicional_b = models.CharField(max_length=255)
```

En este ejemplo, `ModeloBase` es un modelo abstracto que contiene un campo común a ambos modelos. `ModeloA` y `ModeloB` heredan de `ModeloBase` y agregan campos adicionales específicos para cada uno.

Luego, en el archivo `admin.py`, puedes registrar estos modelos:

```python
# admin.py
from django.contrib import admin
from .models import ModeloA, ModeloB

@admin.register(ModeloA)
class ModeloAAdmin(admin.ModelAdmin):
    list_display = ('campo_comun', 'campo_adicional_a')

@admin.register(ModeloB)
class ModeloBAdmin(admin.ModelAdmin):
    list_display = ('campo_comun', 'campo_adicional_b')
```

De esta manera, en el administrador de Django, se mostrarán `ModeloA` y `ModeloB` en una sola tabla con las columnas especificadas en `list_display`. La columna 'campo_comun' es común a ambos modelos, mientras que las columnas adicionales son específicas de cada modelo.

Recuerda realizar las migraciones después de hacer cambios en los modelos:

```bash
python manage.py makemigrations
python manage.py migrate
```

Este es solo un ejemplo básico, y puedes adaptarlo según tus necesidades y la complejidad de tus modelos.
