### ISSUE TITLE
Remove authorizations files when removed

### ISSUE THREAD

**Issue by klautern** [IgnacioMaestro/ampa-manager#34]

**Comment by IgnacioMaestro** [comment]
@classmethod
    def auto_delete_file_on_delete(cls, sender, instance, **kwargs):
        """ Deletes file from filesystem when corresponding object is deleted. """
        if instance.file and os.path.isfile(instance.file.path):
            os.remove(instance.file.path)
    @classmethod
    def auto_delete_file_on_change(cls, sender, instance, **kwargs):
        """
        Deletes old file from filesystem when correspondingobject is updated with new file.
        """
        if not instance.pk:
            return False

        try:
            old_file = Model.objects.get(pk=instance.pk).file
            if not old_file:
                return False
        except ObjectDoesNotExist:
            return False

        new_file = instance.file
        if old_file != new_file and os.path.isfile(old_file.path):
            os.remove(old_file.path)
signals.post_delete.connect(Model.auto_delete_file_on_delete, sender=Model)
signals.pre_save.connect(Model.auto_delete_file_on_change, sender=Model)
