### ISSUE TITLE
Gestion de errores al generar remesas

### ISSUE THREAD

**Issue by klautern** [IgnacioMaestro/ampa-manager#356]
Al generar la remesa de socios de este año a una familia no se le ha emitido recibo.

Al generar cualquier remesa, si algún recibo no se puede crear debería cancelarse el proceso o al menos mostrarle un mensaje al usuario o que quede constancia de alguna forma.

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Update the MembershipRemittanceCreator class to handle cases where a receipt cannot be created for a family. This change will ensure that the process is canceled and an error message is returned if any receipt creation fails.

You can review changes in this commit: https://github.com/mnmnk43434/IgnacioMaestro-ampa-manager-356/commit/27648ca35017e2cce81d74061869bfdafd2fcfb7.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by IgnacioMaestro** [comment]
Yo creo que son 26

**Comment by IgnacioMaestro** [comment]
Corrijo lo que hay que corregir para que no vuelva a pasar
