### ISSUE TITLE
Move membership remittance generation from family ti academic course model

### ISSUE THREAD

**Issue by klautern** [IgnacioMaestro/ampa-manager#62]
Ahora está en las familias. Esto requiere seleccionar todas las familias que se quieren meter en la remesa. Puede ser útil seleccionar solo algunas familias por lo que lo mantendría. Añadiría una acción en el curso academico que busque todas las familias que aún no hayan sido incluidas en una remesa de socios

**Comment by IgnacioMaestro** [comment]
> 

Voy a poner la acción en la remesa de socio, aunque quede un poco raro porque va dar igual que selecciones o no remesas, se va a generar una remesa para el curso activo con las familias que no hayan sido incluidas en una remesa de socios y no tengan el flag de decline_membership
